name: {{implementation_prefix.snakeCase()}}_{{repository_name.snakeCase()}}_api
description: Implementation of {{repository_name.snakeCase()}}_api.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  {{repository_name.snakeCase()}}_api:
    path:
      ../{{repository_name.snakeCase()}}_api

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0
