name: {{repository_name.snakeCase()}}_repository
description: {{repository_description}}.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  {{repository_name.snakeCase()}}_api:
    path:
      ../{{repository_name.snakeCase()}}_api

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.23.1
  very_good_analysis: ^4.0.0+1
